server:
  port: 11000

spring:
  application:
    name: REST-CLIENT


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

#REST-SERVER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


